### PR TITLE
fix the inefficient problem of combine_batches in main_fedavg.py

### PR DESCRIPTION
**Pull request by zzp1012**
simply fix the inefficient problem of combine_batches in main_fedavg.py. After simple test, the program runs correctly.

### CODE REVIEW

**Comment by chaoyanghe** [comment]
@wizard1203 could you help to check if this improves the performance?

**Comment by wizard1203** [comment]
> @wizard1203 could you help to check if this improves the performance?

Seems it can.

**Comment by chaoyanghe** [comment]
@wizard1203 ok. please help to merge after a test.

**Comment by fedml-dimitris** [comment]
Closing the commit, because it refers to an old branch version.

**Pull request closed without merging**
