### PR TITLE
Update README.md in /app/healthcare with appropriate FLamby citation

### PR DESCRIPTION
**Pull request by jeandut**

### CODE REVIEW

**Comment by jeandut** [comment]
@chaoyanghe can you merge this ?

**Comment by jeandut** [comment]
Hi ! 
Can it be merged please ?

**Comment by jeandut** [comment]
Up !

**Comment by Raphael-Jin** [comment]
@chaoyanghe @fedml-alex , please check if we can merge it direct into master, or dev/v0.7.0 first.

**Pull request merged**
